### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by skycaptain** [editorconfig-checker/editorconfig-checker#133]
[pre-commit](https://pre-commit.com/) is a very common tool to execute and manage pre-commit hooks. It would be great to have the ability to use editorconfig-checker as a pre-commit hook using this tool. I've prepared a [mirror](https://github.com/skycaptain/pre-commit-editorconfig-checker) using [pre-commit-mirror-maker](https://github.com/pre-commit/pre-commit-mirror-maker) and your Python wrapper, still it would be great to have this directly in upstream.

EDIT: [I just learned](https://github.com/pre-commit/pre-commit.com/pull/415#issuecomment-723658906) that the Python wrapper is not even needed, since pre-commit supports installing Go repositories directly. However, one might still consider using the Python wrapper as this would install the binary directly without the need of having Go installed, right?

**Comment by mstruebing** [comment]
Thank you very much for your issue @skycaptain :+1: 

To describe what this wrapper does: it downloads a precompiled binary from the releases of the core, so if you are using this wrapper it is not needed to have Go installed, that's right.

Could you describe what needs to be done that this tool is able to be used the way you would want to?

**Comment by skycaptain** [comment]
@mstruebing Thanks for the explanation.

pre-commit has documentation on what needs to be done to add a new hook: https://pre-commit.com/#creating-new-hooks. In short a new file `.pre-commit-hooks.yaml` with some metadata has to added to the project's root, e.g. for the Python wrapper:

```yaml
-   id: editorconfig-checker
    name: editorconfig-checker
    description: '`editorconfig-checker` is a tool to check if your files consider your .editorconfig-rules.'
    entry: editorconfig-checker
    language: python
    types: [python]
    require_serial: true
```

A user can then add your project to their `.pre-commit-config.yaml` like this:

```yaml
repos:
-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.1.0
    hooks:
    -   id: editorconfig-checker
```

The rev field is matching your Git tags you're already using.
