### ISSUE TITLE
⚠️Run fails after v3.1.0 in `editorconfig-checker.javascript`

### ISSUE THREAD

**Issue by lumirlumir** [editorconfig-checker/editorconfig-checker#409]
Hello,

I noticed that version 3.1.0 doesn’t include binary files, which causes CI to fail when running `editorconfig-checker` in a JavaScript environment.  

It seems that `editorconfig-checker.javascript` depends on the GitHub Release Assets, so the binaries should be included.

![image](https://github.com/user-attachments/assets/c49f7969-17bf-4e1b-9c6c-fa010df4b56a)

- Code that I referenced

    - https://github.com/editorconfig-checker/editorconfig-checker.javascript/blob/master/src/index.ts

    - https://github.com/editorconfig-checker/editorconfig-checker.javascript/blob/master/src/constants.ts

- Error Message

    ![image](https://github.com/user-attachments/assets/a73896db-eba2-492b-adc6-43c273115129)

**Comment by A1bi** [comment]
Release pipeline is [broken](https://github.com/editorconfig-checker/editorconfig-checker/actions/runs/12666582550).

**Comment by mstruebing** [comment]
@klaernie @theoludwig do you know if the pipeline uses/have access to the correct secrets?

**Comment by lumirlumir** [comment]
If you're using `editorconfig-checker.javascript`, make sure to add `EC_VERSION` to your `process.env`. This will ensure it works correctly.

- **Example: GitHub Actions**

    ```yaml
    env:
          EC_VERSION: v3.0.3
    ```

**Comment by ngxson** [comment]
For github workflow, you can specify the version number via `inputs`:

```yaml
jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@v2
        with:
          version: v3.0.3
      - run: editorconfig-checker
```
